name: design_system
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_theme: ^4.0.3+1
  flutter_svg: ^1.1.6
  mask_text_input_formatter: ^2.4.0
  flutter_screenutil: ^5.6.0
  modal_bottom_sheet: ^2.1.2
  percent_indicator: ^4.2.2
  expandable_page_view: ^1.0.17
  easy_refresh: ^3.0.4+4
  carousel_slider: ^4.1.1
  shimmer: ^2.0.0
  sliver_tools: ^0.2.8
  flash: ^2.0.5
  pinput: ^2.2.16
  infinite_scroll_pagination: ^3.2.0
  simple_animations: ^5.0.0+2
  logger: ^1.1.0
  readmore: ^2.2.0
  animated_flip_counter: ^0.2.5
  fluttertoast: ^8.1.1
  google_fonts: ^3.0.1

  core:
    path: ../../domain/core
  model:
    path: ../../domain/model

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/
  
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
