name: flutter_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  app_bloc:
    path: app/app_bloc
  feature_home:
    path: app/feature/feature_home
  design_system:
    path: app/design_system
  database:
    path: data/database
  core:
    path: domain/core
  model:
    path: domain/model
  repository:
    path: domain/repository
  usecase:
    path: domain/usecase

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.10.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  flutter_flavorizr: ^2.1.5
  flutter_launcher_icons: ^0.11.0
  injectable_generator: ^1.5.5

flutter:
  uses-material-design: true