name: core
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0
  injectable: ^1.5.4
  auto_route: ^5.0.2

  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.1
  android_id: ^0.1.3+1

  easy_localization: ^3.0.1

  easy_debounce: ^2.0.2+1

  cached_network_image: ^3.2.2
  video_player: ^2.4.7
  story: ^0.8.0

  flutter_multi_formatter: ^2.9.6
  equatable: ^2.0.5
  alice: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0
  injectable_generator: ^1.5.4
  build_runner: ^2.3.2

flutter:

  assets:
    - assets/translations/